//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.DataPipeline
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_configoptions
    {
        public string configName { get; set; }
        public System.DateTime siteLaunchDate { get; set; }
        public double companyClanBattleThreshold { get; set; }
        public double matchHistoryReQueryDays { get; set; }
        public int DNFNeededForLoss { get; set; }
    }
}
