//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.DataPipeline
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h5matches_playersformatch
    {
        public string matchID { get; set; }
        public string team2_Players { get; set; }
        public string team1_Players { get; set; }
        public string other_Players { get; set; }
        public string DNF_Players { get; set; }
    
        public virtual t_h5matches t_h5matches { get; set; }
    }
}
