//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.DataPipeline
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h5matches_teamsinvolved_halowaypointcompanies
    {
        public string matchID { get; set; }
        public string teamSource { get; set; }
        public string team1_Primary { get; set; }
        public string team2_Primary { get; set; }
        public int team1_DNFCount { get; set; }
        public int team2_DNFCount { get; set; }
    
        public virtual t_h5matches t_h5matches { get; set; }
        public virtual t_teamsources t_teamsources { get; set; }
    }
}
