//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.DataPipeline
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_teamsources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_teamsources()
        {
            this.t_h5matches_teamsinvolved_halowaypointcompanies = new HashSet<t_h5matches_teamsinvolved_halowaypointcompanies>();
            this.t_h5matches_teamsinvolved_spartanclashfireteams = new HashSet<t_h5matches_teamsinvolved_spartanclashfireteams>();
            this.t_teams = new HashSet<t_teams>();
        }
    
        public string teamSource { get; set; }
        public string sourceURL { get; set; }
        public string teamCommonName { get; set; }
        public System.DateTime beganTrackingOnDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_h5matches_teamsinvolved_halowaypointcompanies> t_h5matches_teamsinvolved_halowaypointcompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_h5matches_teamsinvolved_spartanclashfireteams> t_h5matches_teamsinvolved_spartanclashfireteams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_teams> t_teams { get; set; }
    }
}
