//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.SpartanClash
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clashdbEntities : DbContext
    {
        public clashdbEntities()
            : base("name=clashdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_clashdevset> t_clashdevset { get; set; }
        public virtual DbSet<t_clashmetadata> t_clashmetadata { get; set; }
        public virtual DbSet<t_companies> t_companies { get; set; }
        public virtual DbSet<t_mapmetadata> t_mapmetadata { get; set; }
        public virtual DbSet<t_matchparticipants> t_matchparticipants { get; set; }
    }
}
