//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.SpartanClash
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_companies()
        {
            this.t_clashdevset = new HashSet<t_clashdevset>();
        }
    
        public string companyId { get; set; }
        public string companyName { get; set; }
        public int waypointLeaderBoardRank { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> losses { get; set; }
        public Nullable<int> total_matches { get; set; }
        public Nullable<double> win_percent { get; set; }
        public int times_searched { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_clashdevset> t_clashdevset { get; set; }
    }
}
