//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models.SpartanClash
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_mapmetadata
    {
        public string mapId { get; set; }
        public string printableName { get; set; }
        public string imageURL { get; set; }
    }
}
