//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dev_spartanclashbackendEntities : DbContext
    {
        public dev_spartanclashbackendEntities()
            : base("name=dev_spartanclashbackendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_h5matches> t_h5matches { get; set; }
        public virtual DbSet<t_h5matches_matchdetails> t_h5matches_matchdetails { get; set; }
        public virtual DbSet<t_h5matches_playersformatch> t_h5matches_playersformatch { get; set; }
        public virtual DbSet<t_h5matches_ranksandscores> t_h5matches_ranksandscores { get; set; }
        public virtual DbSet<t_h5matches_teamsinvolved_halowaypointcompanies> t_h5matches_teamsinvolved_halowaypointcompanies { get; set; }
        public virtual DbSet<t_h5matches_teamsinvolved_spartanclashfireteams> t_h5matches_teamsinvolved_spartanclashfireteams { get; set; }
        public virtual DbSet<t_players> t_players { get; set; }
        public virtual DbSet<t_players_to_teams> t_players_to_teams { get; set; }
        public virtual DbSet<t_teams> t_teams { get; set; }
        public virtual DbSet<t_teamsources> t_teamsources { get; set; }
    }
}
