//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h5matches_teamsinvolved_spartanclashfireteams
    {
        public string matchID { get; set; }
        public string teamSource { get; set; }
        public string team1_Primary { get; set; }
        public string team2_Primary { get; set; }
        public string team1_Secondary { get; set; }
        public string team2_Secondary { get; set; }
    
        public virtual t_h5matches t_h5matches { get; set; }
        public virtual t_teamsources t_teamsources { get; set; }
    }
}
