//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_players_to_h5matches
    {
        public string gamertag { get; set; }
        public string matchID { get; set; }
        public string dummyColumnAboutAssociation { get; set; }
    
        public virtual t_h5matches t_h5matches { get; set; }
        public virtual t_players t_players { get; set; }
    }
}
