//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5_DataPipeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_teams()
        {
            this.t_players_to_teams = new HashSet<t_players_to_teams>();
        }
    
        public string teamId { get; set; }
        public string teamName { get; set; }
        public string teamSource { get; set; }
        public int trackingIndex { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public Nullable<System.DateTime> rosterLastUdated { get; set; }
        public string parentTeamId { get; set; }
        public string parentTeamName { get; set; }
        public string parentTeamSource { get; set; }
        public System.DateTime beganTrackingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_players_to_teams> t_players_to_teams { get; set; }
        public virtual t_teamsources t_teamsources { get; set; }
    }
}
